### ISSUE TITLE
The djangae.contrib.backup app is a pain to use

### ISSUE THREAD

**Issue by davidwtbuxton** [potatolondon/djangae#1004]
2 things annoy me when using the djangae.contrib.backup application.

First is the need to configure the bucket name (which should default to the application's default bucket name) and a name for the backup (which should default to something sensible like "djangae-backups"). It should be enough to just set `DJANGAE_BACKUP_ENABLED = True` and you're done. Those projects that need to fine tune the settings can continue to do so.

Second is that the backups are always created in the same directory in the bucket. Because the Google datastore backup format is somewhat crazy (a bunch of files and directories with totally meaningless random names) this means you quickly have a backup directory full of hundreds (if not thousands) of objects, and identifying the most recent backup, or what backups have been created, is tedious from the Google Cloud Storage browser.

What would be much nicer is if the backups were created with a new directory each time, with the new directory name including a timestamp. Something like "myapp.appspot.com/djangae-backups/20171127-235900/". That way it would be easy to tell when backups were created, etc.

Third, the documentation is out of date.

Can I fix?

Dave

**Comment by adamalton** [comment]
I've never used it, but they sound like good changes to me!

**Comment by davidwtbuxton** [comment]
@nealedj Opinions?

**Comment by nealedj** [comment]
> First is the need to configure the bucket name

Sounds like a good idea! The backup app evolved out of the datastore admin [scheduled backups](https://cloud.google.com/appengine/articles/scheduled_backups) where the bucket name is required. Defaulting it to the apps default bucket seems reasonable to me.

> Second is that the backups are always created in the same directory in the bucket.
I agree that this is annoying. Although ideally I wish that GCS would provide the ability to enumerate files sorted by timestamp since it's generally only recent backups that are of interest.

I don't know of anything that relies on the backup structure. The datastore admin UI enumerates recent backups but I'm guess that this is based on map reduce job markers rather than the raw backup files.

> Third, the documentation is out of date.
Since nothing's changed in the backup app since this was merged I'd say I just wrote some incorrect docs. Fixups very welcome!
