### ISSUE TITLE
Add remove_duplicates option to ListField/RelatedListField

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#1017]
## Issue description

We give two main options for storing arrays of data on a model, these are `ListField` and `SetField`. The advantage of `ListField` is that it remains ordered, whereas the advantage of `SetField` is that it's not possible that it can contain duplicate entries.

However, sometimes you need order, but also to not duplicate values (in fact, that's fairly common in `ListFields`). It's simple enough to remove duplicates and retain order so I suggest we add a `remove_duplicates` keyword argument to `ListField` (defaulting to `False`) which when saving will remove any duplicated elements. 

We should also add this to `RelatedListField` if we are adding it to `ListField`

**Comment by adamalton** [comment]
If there's a duplicate, which one does it remove?

Would it make sense to allow a `sort` function as a kwarg?

**Comment by Kazade** [comment]
I don't understand...

If it's a duplicate, it'll probably keep the first one and remove all others. We already have a way of specifying the ordering.

**Comment by adamalton** [comment]
> it'll probably keep the first one
My point is, should we make that ^ a defined behaviour?

> We already have a way of specifying the ordering.
Ah yes, so we do!  You can ignore that comment then!

**Comment by adamalton** [comment]
I guess if you're bothered about the ordering, you'll specify an ordering, in which case we don't need to define which of the duplicates gets deleted.

Just ignore me entirely!

**Comment by davidwtbuxton** [comment]
How about an OrderedSetField, rather than overloading the semantics of a ListField?

**Comment by davidwtbuxton** [comment]
I still think OrderedSetField and OrderedRelatedSetField would be better than adding a keyword that changes the behaviour of the existing field types.

I think having new types would:

- Make it more obvious when reading the code that this field does not behave the same as ListField.
- The name OrderedSetField itself is a better indication of what to expect for the behaviour (rather than a new keyword).
- Will make the code simpler because the implementation will be in a separate class to ListField, so we can be more confident that it will have no impact on the existing behaviour of ListField.
