### ISSUE TITLE
Update ``sleuth`` to allow decorating of whole test cases.

### ISSUE THREAD

**Issue by robcharlwood** [potatolondon/djangae#1025]
currently sleuth does not support being applied at class level. For example, I would expect the below to work, but it doesn't.

We should update the decorator to allow class level decorating.

```
@sleuth.fake('my.thing.to.fake', return_value=True)
class MyTestClass(TestCase):
    def test_my_thing(self):
        pass
```

**Comment by adamalton** [comment]
The thing with doing this is that you then have to define what decorating the class should actually do.  Does it activate the patch when the class is instantiated?  When each method is called?  When each method that begins with `test_` is called?  If the latter, should the 'fake' object be available inside the methods?  And if so, should it be accessible as an attribute on the object, or should it be passed to each method as an extra parameter?

It then becomes very specific to test cases.  And what seems like an obvious and straightforward "just decorate the class" actually has a load of extra implicit behaviour.

I'm not saying that we shouldn't do it.  But I'm wondering whether we should do it via an extra separate function, e.g.:

```context_manage_test_methods(
    sleuth.fake('my.thing.to.fake', return_value=True),
    pass_as_param="faker"
)
class MyTestClass(TestCase):
    def test_my_thing(self, faker=None):
```

Which would avoid "polluting" sleuth with a bunch of magical functionality.

Counter argument: sleuth is only for testing anyway, so it doesn't matter.

Thoughts?

**Comment by davidwtbuxton** [comment]
This feature is in Mock.

https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch

> Patch can be used as a TestCase class decorator. It works by decorating each test method in the class. This reduces the boilerplate code when your test methods share a common patchings set. patch() finds tests by looking for method names that start with patch.TEST_PREFIX. By default this is 'test', which matches the way unittest finds tests. You can specify an alternative prefix by setting patch.TEST_PREFIX.

Instead of adding each missing feature, we should stop using Sleuth and use Mock.

Mock is in the standard library since Python 3.3. It is the de facto mock/test library for Python 2.x. It has more features and better documentation than Sleuth.

**Comment by Kazade** [comment]
This ticket should be under the sleuth project, not here: https://github.com/kazade/sleuth

As for whether to switch to mock or not. My opinion is mock's API is confusing and hard to use. It's only frustration at being unable to figure out how to do things with it that led to sleuth in the first place.

I feel that sleuth's explicit and isolated fake/switch/watch calls make for more readable test cases  than mock and it's a much more targeted library; only focusing on watching/manipulating function calls rather than objects.

Obviously opinions vary.

As for it being standard in Python 3, when we port to 3 I'll consider it again but it doesn't seem worth switching right now, especially as we don't actually need this ticket's functionally in Djangae at the moment.
