### ISSUE TITLE
values_list returns str instead of unicode when using the datastore backend

### ISSUE THREAD

**Issue by sleepyjames** [potatolondon/djangae#1026]
When calling `values_list` on a queryset that uses the datastore backend eg: `MyModel.objects.all().values_list('some_charfield', flat=True)` strings are returned as `str` not `unicode`. This differs from the encoding when accessing the property on a regular model instance, which always returns unicode.

Steps to reproduce:

my_model.py
```
class MyModel(models.Model):
    foo = models.CharField(max_length=100)
```
```
python manage.py shell
...
> x = MyModel.objects.create(foo=u'bar')
...
> type(MyModel.objects.get(pk=x.pk).foo)
<type 'unicode'>
> type(MyModel.objects.filter(pk=x.pk).values_list('foo', flat=True)[0])
<type 'str'>
```

When using a regular database backend `values_list` always returns it's strings as unicode.

* Djangae version: master@844439839939a792a862660953c0c85f4d0c4096
* Django version: 1.11.0
* App Engine SDK version: 1.9.57
* Using Cloud SDK: yes

**Comment by Kazade** [comment]
Turns out this is a bug in App Engine. In datastore_types.py there is this function:

```
def FromPropertyPb(pb):
  """Converts a property PB to a python value.
```

In there, is the following code:

```
  pbval = pb.value()
  meaning = pb.meaning()

  if pbval.has_stringvalue():
    value = pbval.stringvalue()
    if not pb.has_meaning() or meaning not in _NON_UTF8_MEANINGS:
      value = unicode(value, 'utf-8')
```

When you perform a projection query, the "meaning" is `entity_pb.Property.INDEX_VALUE` and for some reason that's in `_NON_UTF8_MEANINGS` and so the conversion never happens.

This means it affects `.only()`, `.defer()`, `.values()` and `.values_list()`

I'll workaround it.

**Comment by sleepyjames** [comment]
Just noticed this. Thanks for the fix :-)
