### ISSUE TITLE
PositiveIntegerField allows negative values

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#1032]
It seems that if you have a `PositiveIntegerField` on a model, then you can save negative values into it.  It "works" perfectly, the values are saved to the Datastore and returned as normal.  But presumably this should raise an IntegrityError?  (Because on SQL the INT/BIGINT column would be unsigned.)

* Djangae version: 0.9.9
* Django version: 1.9
* App Engine SDK version: 1.9.38
* Using Cloud SDK: no

**Comment by Kazade** [comment]
So it turns out this isn't a bug as such...

There are two differences between `PositiveIntegerField` and `IntegerField`. The first is this:

```
    def formfield(self, **kwargs):
        return super().formfield(**{
            'min_value': 0,
            **kwargs,
        })
```

So, a form.full_clean() will correctly raise a `ValidationError` if you enter a negative number. The second, is this here: 

```
    def get_internal_type(self):
        return "PositiveIntegerField"
```

Which is correctly keyed here in the base connector `DatabaseOperations` class:

```
    integer_field_ranges = {
        'SmallIntegerField': (-MAXINT, MAXINT-1),
        'IntegerField': (-MAXINT, MAXINT-1),
        'BigIntegerField': (-MAXINT, MAXINT-1),
        'PositiveSmallIntegerField': (0, MAXINT-1),
        'PositiveIntegerField': (0, MAXINT-1),
    }
```

`integer_field_ranges` is only ever called by `integer_field_range` which is only called in one place.. here in the `IntegerField` class when generating validators:

```
    @cached_property
    def validators(self):
        # These validators can't be added at field initialization time since
        # they're based on values retrieved from `connection`.
        validators_ = super().validators
        internal_type = self.get_internal_type()
        min_value, max_value = connection.ops.integer_field_range(internal_type)
```

There's nothing in Django that enforces this aside from at the form level. But you could argue that we take over the Database constraint layer in Djange and we could raise an error before saving, but then if you take at the SQLite database connector...

```
    def integer_field_range(self, internal_type):
        # SQLite doesn't enforce any integer constraints
        return (None, None)
```

And indeed, the issue occurs on that connector too: https://stackoverflow.com/questions/29067045/django-positiveintegerfield-accepting-negatives

So the question is, do we do zig and do what Django does (and do nothing) or do we zag and raise an IntegrityError if this happens?

I'm inclined to raise the error, because that's probably the path of least surprise and may catch so difficult repair bugs.

@adamalton thoughts?

**Comment by Kazade** [comment]
There's also a question about where best to raise the error. To match SQL it needs to raise just as we `Put()` but there are two problems with that:

1. We don't know what the field was at that point
2. If we're bulk inserting we'll may have some entities already `Put()` when we raise, and how does the user recover from that?

The other option is in `django_instance_to_entities` (which I believe - hope - is only called from `InsertCommand` and `UpdateCommand` which will raise when preparing to insert. That's probably best, but it feels a bit odd there.

**Comment by Kazade** [comment]
To be fixed in Djangae 2.x (see https://github.com/potatolondon/django-gcloud-connectors/issues/14)
