### ISSUE TITLE
Make __in queries with greater than 30 elements "just work"

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#140]
Historically, djangoappengine and djangae have thrown an error if you attempt to do a filter on more than 30 elements. This is because that's the limit for what you can do in a single MultiQuery on the datastore.

When someone hits this limit though, the solution is nearly always to batch their queries into groups of 30. Making users reinvent the wheel here every time is not ideal, especially as a naive implementation could end up with duplicate results (the same element could be returned in two or more of the batched queries).

It would make sense if we just handled this on the connector. We should display a warning locally when this happens. We can also optimize this by making a series of async queries. The results will have to go through a de-duplicating generator.

**Comment by adamalton** [comment]
My general thinking here is that when you're doing something which is inefficient (e.g. a query which requires a MultiQuery of more than 30) you should know about it.  If we make things like this "just work" then people won't know when they're doing things inefficiently.

The App Engine/Datastore way is to force you to write things in a way that will scale, and using crazy numbers of MultiQueries isn't necessarily very scalable, so I think it's good to make people deal with these things manually so that if they do do crazy things then at least it's deliberate.

Closing for now.
