### ISSUE TITLE
Indexing Documentation

### ISSUE THREAD

**Issue by sebastianmacias** [potatolondon/djangae#151]
First of all, thanks for working on this. 

I'm testing djangae and I keep getting errors like this:

```
add_special_index
    _get_table_from_model(model_class), field_name, index_type
RuntimeError: There is a missing index in your djangaeidx.yaml - 

account_emailaddress:
	email: [iexact]
```

How can we create djangaeidx.yaml, is there an index auto creation tool? If there isn't, can you please post a sample djangaeidx.yaml?

Thanks

**Comment by adamalton** [comment]
This is covered in the [README](https://github.com/potatolondon/djangae#the-database-backend).  If you set `settings.GENERATE_SPECIAL_INDEXES_DURING_TESTING` then the indexes will be automatically generated during tests, but otherwise they will only be automatically generated when running the development server and will raise errors in tests.

**Comment by adamalton** [comment]
I'm going to close this as I think it's suitably covered in the [docs](https://djangae.readthedocs.org/en/latest/db_backend/), but re-open if you think it needs more explanation.

**Comment by Ali-aqrabawi** [comment]
I have same issue, how can i use GENERATE_SPECIAL_INDEXES_DURING_TESTING  ? where should i add this in my code ?

**Comment by adamalton** [comment]
It just goes in the normal Django settings file: https://docs.djangoproject.com/en/1.10/topics/settings/
