### ISSUE TITLE
Add deferred task processor in tests

### ISSUE THREAD

**Issue by BogdanL** [potatolondon/djangae#157]
At the moment there's no Djangae way of running deferred tasks in tests, the workaround being mocking defer to run the deferred function straight away. Something like TaskQueueProcessor would be quite handy.

**Comment by adamalton** [comment]
This might be partly fixed in #169.

It didn't add a mock for directly patching `defer.deferred`, but it's added a `process_task_queues()` thing.

@Kazade was saying that directly patching `defer.deferred` to run immediately is a bit nasty, because it doesn't mimick real behaviour (i.e. it makes things run *immediately*, rather than asynchronously), so calling `process_task_queues()` is probably a better way of doing it.

I'm going to close this, but if you'd like a defer patcher, then you can submit a PR, @BogdanL :-)

**Comment by BogdanL** [comment]
That's exactly what I was hoping for – TaskQueueProcessor.process_task_queues().
