### ISSUE TITLE
runserver does not respect --settings flag

### ISSUE THREAD

**Issue by adamalton** [potatolondon/djangae#249]
If you run `$ python manage.py runserver --settings=my_settings` then the `my_settings` module does not get used as your settings file.

Or rather, it does get used, but then gets overridden.  In djangae/management/commands/runserver.py in `Command.inner_run` circa line 42 where the `self.stdout.write` stuff happens, settings is correctly set up, but by the time it gets to your application code it has reverted.

**Comment by Purpwood** [comment]
The `runserver` settings flag sets the `DJANGO_SETTINGS_MODULE` environment variable correctly, but when we get to our WSGI we don't have access to environment variables. This is because `os.environ` [shadows the WSGI environment instead] (http://stackoverflow.com/questions/11064900/how-to-make-changes-to-os-environ-dict-available-application-wide#answer-11066926).
