### ISSUE TITLE
Add CSP reporting to djangae.contrib.security

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#272]
It would be good to have an off-the-shelf way to hook up CSP violation reports.

**Comment by stucox** [comment]
How about a custom `/_ah` URL which just spits the report out as a warning in the logs? Or even an error?

**Comment by adamalton** [comment]
I've already written a [library for this](https://github.com/adamalton/django-csp-reports) a while ago.  So rather than copy-pasta-ing anything, I'll just add it to the libraries in Djangae Scaffold (alongside django-csp, etc).

The library allows you to log things to the logs and/or database and/or email.

I'm closing this and will do the work on here: https://github.com/potatolondon/djangae-scaffold/issues/28
