### ISSUE TITLE
In-context cache isn’t cleared after tests

### ISSUE THREAD

**Issue by stucox** [potatolondon/djangae#322]
We found cases where `MyModel.objects.all()` would return an empty set, but `MyModel.objects.get(...)` immediately after this would return an item.

Didn’t occur when this test was run in isolation; only when several were run together.

Adding `clear_context_cache()` to our test `tearDown()` fixes this.

I’m afraid I haven’t managed to create a reduced test case yet.

If this is required, maybe it should be added to `djangae.test.TestCase`? (which in turn could do with a mention in the README)

**Comment by Kazade** [comment]
So, this shouldn't happen, because:

 1. At the end of each test, Django flushes the database tables
 2. This should execute an instance of FlushCommand (see djangae/db/backends/appengine/commands.py) which calls clear_cache and clear_context_cache.

We need to determine if flush is being called. I haven't seen this bug on any project so far, and I'm pretty sure I would've noticed, so it might be something special with your project setup.

**Comment by Kazade** [comment]
Imma close this until you can prove it @stucox  ;)
