### ISSUE TITLE
Does JSONField really belong in Djangae?

### ISSUE THREAD

**Issue by stucox** [potatolondon/djangae#324]
Is there anything App Engine specific about `djangae.fields.json.JSONField`?

If not, I propose we remove it and leave that responsibility to other libs, like [this one](https://github.com/bradjasper/django-jsonfield) – and only include things which require some kind of GAE-specific handling in Djangae.

**Comment by Kazade** [comment]
Technically no there is nothing App Engine specific about it. However, the non rel nature of the datastore makes it damn near necessary for denorm, and it's a far better solution than Django toolbox's DictField. Because its a single class, and it makes everyone's lives easier, I think it's more helpful and easier to bundle it, than to repeatedly direct people elsewhere, so "won't fix" I'm afraid :)

Totally understand where you are coming from though!

**Comment by Kazade** [comment]
Saying that though, I'll happily accept a PR that moves it to djangae.contrib.common.fields instead

**Comment by stucox** [comment]
So it's there as an easy upgrade path from `djangotoolbox.fields.DictField`?

In which case it could do with some upgrade documentation, cos that ain't an easy migration.

**Comment by stucox** [comment]
And maybe consider bundling the [bradjasper version](https://github.com/bradjasper/django-jsonfield)? Which has support for things like custom encoders, OrderedDicts, has a JSONCharField in case you need it to be indexable, etc.
