### ISSUE TITLE
abstract shard counting to support custom scopes

### ISSUE THREAD

**Issue by jacobg** [potatolondon/djangae#410]
A scenario is to be able to count model entities per user, customer, account, or whatever. GAE itself does this by providing datastore statistics for each model per app. It would be great for the shard counting functionality to support this scenario by abstracting base classes that can be extended to add a set of scoped fields (i.e., count per set of unique fields).

**Comment by jacobg** [comment]
Just to clarify, I understand that the ShardedCounterField is a related counter to an entity. The scenario I am discussing is where it's not a related field, in order that it not be necessary to define all the counter fields on any other model (or perhaps such a model does not exist).

**Comment by adamalton** [comment]
This seems like functionality which is outside of the scope of Djangae.  Although it might be possible to make it generic, I don't see a reason for putting this into Djangae rather than putting it into a separate Django app.

> Perhaps it could be a kind of reverse related field on the actual model that is being counted.

A reverse related field only works on an **instance** of a model, not on a model.

> be able to count model entities per user, customer, account, or whatever

if you want to count something per user, then why not just have a ShardedCounterField on the User model for counting that?

If I'm understanding this correctly then none of it seems like it would require anything fundamental which isn't already provided by Djangae.  I think it's just a case of creating a model structure with the necessary counters which serve the purposes of your project.

**Comment by jacobg** [comment]
Thanks Adam. I hear you, and I appreciate the time you took to understand my problem and respond.

I ended up making a solution using an abstract model mixin to intercept the clean and save methods.
