### ISSUE TITLE
Suggestion: remove ALLOWED_HOSTS restriction

### ISSUE THREAD

**Issue by jasoncartwright** [potatolondon/djangae#421]
Given that App Engine & Google Apps manages the mapping of a domain name to an App Engine application and defines which host an App Engine app can respond to ALLOWED_HOSTS is redundant.

Perhaps this restriction should be removed to aid deployment of apps and confusion when they return 400s in different environments?

**Comment by adamalton** [comment]
I'm tempted to say that this should actually be fixed in Django.  The reason why it's so confusing is because the 400 response doesn't log an error.  If Django logged an error then people wouldn't be confused by this.

That's not to say that we can't set `ALLOWED_HOSTS = '*'` for App Engine, but it's bordering on going against the "secure by default" principle.

**Comment by Kazade** [comment]
I reckon lets set `ALLOWED_HOSTS = '*'` in settings_base.py. We're pretty sure it's not a security issue on App Engine, and Djangae is only for App Engine. We should document this, and probably file a bug with Django about giving some sensible logging when this happens

**Comment by Kazade** [comment]
Patches welcome @jasoncartwright  ;)
