### ISSUE TITLE
gauth: Lowercase email addresses for lookups and creation

### ISSUE THREAD

**Issue by martinallison** [potatolondon/djangae#481]
Semi-related to #461.

The fix for #461 removed the `email = email.lower()` line in `common.backends`. Rather than doing that, I think a better fix would have been to add `lower()` to everywhere where the email is normalised (since, `BaseUserManager` doesn't do that as part of normalisation.)

Oftentimes the reason for using user pre-creation is for when someone invites a user to a system and then that user logs in and everything is magically already hooked up.

This doesn't work if user A invites 'person@gmail.com' but user B logs in with 'Person@gmail.com'. User B shouldn't have to care what case their email was written in when they were invited.

Currently, to customise this behaviour, you'd have to make your own copies of `gauth.common.backends.BaseAppEngineUserAPIBackend` and `gauth.middleware.AuthenticationMiddleware`. It'd be nice to either do it by default (but provide a 'migration' to not break everyone else already relying on this behaviour) or have some other way of being able to do it.

Of course ideally the App Engine User's API would just lowercase everything all the time.

**Comment by Kazade** [comment]
@adamalton your thoughts?

**Comment by adamalton** [comment]
This is one of those things where technically email addresses are case sensitive but in reality none of the email servers that anyone actually uses actually allow variations in case to differentiate between accounts.

I know that Google Accounts is case sensitive with regard to email addresses, because it has to be; you can create a Google Account using a non-Gmail email address, and because Google can't guarantee that the email provider of the given email address doesn't treat things case sensitively, it has to assume that it does.  For Gmail addresses we can assume that case doesn't matter, but for Google Accounts in general we *technically* should treat them as case sensitive.

I'm torn.  Technically we should keep the case sensitivity, but pragmatism says that keeping it will cause way more problems than it solves.

I can think of 4 possible solutions:

1. Customise `normalize_email` to include an `if domain in "gmail.com", "googlemail.com"...email.lower()` special case.  This would *partly* solve the problem.
2. Given that the only time we authenticate against the email address (rather than the User ID) is when we pre-create a user, change the logic so that if `username is None` (i.e. if we're pre-creating) then lowercase the email before saving, do the "is there a pre-created user?" lookup in lowercase, and then re-save it with the original case after the user logs in (because we then have their User ID).
3. Always lowercase the email because that's what 99% of the world does.
4. Leave it as it is and force people to get the case right.

I'm thinking probably *2.* or *3.*, but without an in-person discussion I'm failing to choose.

**Comment by martinallison** [comment]
So perhaps don't do anything by default but instead expose a hook _somehow_ to provide your own normalization function (which is called after Django's) because, another fun thing has popped up that I forgot about when I first wrote the ticket: gmail.com addresses are insensitive to dots in the username part of the email...

Part of me feels like it's a bit wrong to hard-code this behaviour in djangae itself, but the other part says that it is a backend for specifically Google Account auth, so it should probably just deal with these things.

The approach we've taken is:

* Patch `BaseUserManager.normalize_email` to lowercase and, if it's a gmail.com account, strip the dots - this means that pre-creation and lookups on email work properly for all accounts (barring Adam's point about lowercasing above - we're taking the risk assuming it's OK)
* Keep a `display_email`/`raw_email`/whatever field with the raw email address that came from the Users API
