### ISSUE TITLE
Raise `NotSupportedError` for `select_related` and `prefetch_related` queries

### ISSUE THREAD

**Issue by pablorecio** [potatolondon/djangae#505]
This way, we don't hide the fact they are not doing nothing under the hood as it'll have to do a query pero row anyway due the lack of JOIN queries.

**Comment by Kazade** [comment]
`prefetch_related` actually works surprisingly! 

But yeah, we should do this rather than manually disabling `select_related` - because otherwise people will believe it's doing something.

**Comment by Kazade** [comment]
Thinking about it, it's probably better to document this (loudly), rather than throw an error. The reason is that the current behaviour (ignoring `select_related`) allows you to use third-party libraries without changes even though it may be slow. 

`prefetch_related` works perfectly on the datastore - so this is only for the `select_related` case.
