### ISSUE TITLE
Improve thread-safety of memcache usage

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#575]
This just occurred to me.. imagine the following process:

1. Request A calls Put
2. Request B calls Put
3. Request B updates memcache
4. Request A updates memcache
5. Bugger.

In practice this is unlike to happen as Djangae only ever updates inside a transaction and the two transactions would likely collide, still there is a very real race condition here.

We should look into how NDB handles this, and if possible, write some tests to test this can't happen. Also useful: https://cloud.google.com/appengine/articles/best-practices-for-app-engine-memcache

**Comment by adamalton** [comment]
Are you talking about when those `Put`s are inside a transaction?

If they're **not** inside a transaction then there's a race condition anyway, so you wouldn't know if the other thread had overwritten your `Put` or not.  I guess memcache makes that situation a bit more screwed up though.

If they **are** inside a transaction, then yes, the scenario you've given is unlikely but possible, and would be bad.

Here's a controversial idea:

* Remove the memcache caching :scream: 
* Keep only the context caching, because
  1. It's faster and therefore is a smaller burden for cache misses and a gives greater benefit for cache hits.
  2. It doesn't suffer from the problem you've described.  (I don't think?)
* Maybe start using the unique markers to speed up queries for unique(_together) things now that memcache is ditched.

Plan B (taken from that doc):

* When updating entities, don't call `memcache.set()` with the new value, just call `memcache.delete()`.
* Then when fetching objects, try `memcache.get()` and if we get `None` then fetch from the Datastore and then call `memcache.set()`.

You would think that would solve the problem, but I don't think it does, because now we're calling `set()` outside of a transaction, which causes a race condition in a different way!

Another different but related problem: we're not checking the return value of `.set()` calls, so if we fail to update an existing record in memcache then we don't know about it.

My overall feeling is that there's something wrong with our approach to `save()` - the fact that we re-fetch the entity from the Datastore, but then overwrite the values for *all* of the model fields, even if they haven't changed, which seems a bit like we're fetching the existing object to "update" it, but then we're just overwriting everything.  And the fact that in a transaction when you do:

```with transaction.atomic():
    obj = obj.__class__.objects.get(pk=obj.pk)
    fiddle(obj)
    obj.save()
```

you're actually fetching the object twice, once explicitly and again in the `save()`, which just seems like a really weird workflow.

I'm not sure what the answer to all this is, but I have a feeling that it's going to be an extreme answer which we won't like!

**Comment by Kazade** [comment]
> Are you talking about when those Puts are inside a transaction?

Yes

> If they're not inside a transaction then there's a race condition anyway, so you wouldn't know if the other thread had overwritten your Put or not. I guess memcache makes that situation a bit more screwed up though.

Yeah, ignore the outside transaction thing, I'm talking about a mismatch between datastore and memcache.

> Plan A stuff

No, because the memcache cache is where the most benefit is seen - it's not often that you refetch the same object by key twice in the same request in comparison to how often you do in separate requests (memcache)

> Plan B (taken from that doc):
> 
>     When updating entities, don't call memcache.set() with the new value, just call memcache.delete().
>     Then when fetching objects, try memcache.get() and if we get None then fetch from the Datastore and then call memcache.set().

Is that what NDB does? Isn't that what we're doing?

> You would think that would solve the problem, but I don't think it does, because now we're calling set() outside of a transaction, which causes a race condition in a different way!

No it doesn't. It would set whatever is in the datastore, we never call set() inside a transaction anyway because that would be madness.

> Another different but related problem: we're not checking the return value of .set() calls, so if we fail to update an existing record in memcache then we don't know about it.

Meh, I guess if we can't set we should at least then delete.

> My overall feeling is that there's something wrong with our approach to save() - the fact that we re-fetch the entity from the Datastore, but then overwrite the values for all of the model fields, even if they haven't changed, which seems a bit like we're fetching the existing object to "update" it, but then we're just overwriting everything. And the fact that in a transaction when you do:
> 
> with transaction.atomic():
>     obj = obj.__class__.objects.get(pk=obj.pk)
>     fiddle(obj)
>     obj.save()
> 
> you're actually fetching the object twice, once explicitly and again in the save(), which just seems like a really weird workflow.

If we don't do that, do you realize how bad that is? The "db.transactional" wrapper would be pointless (and so we'd remove it) and then we're basically blindly writing over stuff, losing properties that were updated in other requests. It's not ideal but the datastore doesn't provide us with an update() so our hands are tied.

Anyway, I've actually realized this isn't a problem - because we don't cache on put, we wipe the cache on put like we're supposed to:

```
    if situation in (CachingSituation.DATASTORE_PUT, CachingSituation.DATASTORE_GET_PUT) and datastore.IsInTransaction():
        # We have to wipe the entity from memcache
        _remove_entities_from_memcache_by_key([entity.key() for entity in entities if entity.key()], namespace)
```

IsInTransaction always returns True on an update or Insert.
