### ISSUE TITLE
Make memcache.set calls async

### ISSUE THREAD

**Issue by Kazade** [potatolondon/djangae#578]
This is an easy win. We never rely on the return value from memcache.set - so we should do this async. This will provide a large speed up for everyone.

It looks like App Engine doesn't expose set_multi_async on the global client, so we'll need to instantiate either a local client, or a thread-specific one.

**Comment by adamalton** [comment]
`google.appengine.api.memcache.Client` has a `set_multi_async` method, it's just that Django's `MemcachedCache` backend doesn't pass it through.

So I think we have 3 options:

1. Call `google.appengine.api.memcache.Client.set_multi_async` directly (and have to deal with things like Django's `CACHE_PREFIX` manually).
2.  Create a new cache backend called `MemcachedAsync` which does its `set()`-ing asynchronously, and specify it as a separate cache in `settings.CACHES` so that we can then do `django.core.cache.caches['async'].set(key, value)`.
3. Create a new cache backend which just has an _extra_ method called `set_multi_async` on it.  We then set that as the `'default'` cache backend and can then just do `django.core.cache.set_multi_async` because our backend with that extra method will be the default cache.

I vote for 3.

**Comment by Kazade** [comment]
I actually think 1. - because if you do 3. and someone changes the memcache backend everything breaks!

Also, like I said, `set_multi_async` isn't exposed on the global client so we have to instantiate our own client regardless.

**Comment by adamalton** [comment]
Good point re. people changing `settings.CACHES`.  Which makes me think we should _always_ be going directly to `google.appengine.memcache` for all of our DB caching operations so that we are immune to people changing the cache settings.

I can't even see where `google.appengine.api.memcache.get/set/etc` get defined!  They don't appear to be anywhere in `google/appengine/api/memcache/__init__.py`..?!  Confused :confused:
