### ISSUE TITLE
Is there a way to create and authenticate users without depending on Google Account

### ISSUE THREAD

**Issue by juliocebrito** [potatolondon/djangae#753]
Hi, I'm trying to create and authenticate users, using the GaeDatastoreUser model. But I want to allow the creation of users from outside the context of Google Accounts, is there a way to achieve this?

Thanks in advance.

**Comment by adamalton** [comment]
Do you mean that you want to be able to authenticate the users with a
normal username/password?

It is in theory possible to use the standard `django.contrib.auth`
middleware and authentication backend alongside the `djangae.contrib.gauth`
ones.  I don't think it's detailed in the docs, but you should be able to
use both at the same time, using the GaeDatastoreUser model.

**Comment by juliocebrito** [comment]
Thank you.
We could solve it by extending from those modules.

**Comment by adamalton** [comment]
One thing I forgot to mention is that you can use djangae auth things and
django auth things alongside each other, but authenticating the same user
with both Google Accounts and a username/password would be rather tricky.
This is because users created with Google Accounts authentication have
their `username` field set to the Google Accounts user ID, and have a
password of None set, which is unusable.  So for that user to also be able
to log in with a username and password, their username would have to be
their Google Accounts user ID and they would need to somehow reset their
password first.

Adam
