### ISSUE TITLE
Port binding not able to determine which ports are in use

### ISSUE THREAD

**Issue by farridav** [potatolondon/djangae#773]
Google groups thread: https://groups.google.com/forum/#!topic/djangae-users/79eVa24vD6g

The code Djangae uses to determine which port is open, appears unable to do so, see:

```
15:41:23 -> lsof -i tcp:8080
COMMAND PID    USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
java     61 jenkins  169u  IPv6 0x8d3a6d70b7f9cc67      0t0  TCP *:http-alt (LISTEN)
```

```
15:37:31 -> ./manage.py shell
INFO     2016-10-27 15:37:40,451 blobstore_service.py:73] Starting blobstore service on localhost:8080

In [1]: from djangae.utils import get_next_available_port
In [2]: get_next_available_port('0.0.0.0', 80)
Out[2]: 80
In [3]: get_next_available_port('0.0.0.0', 8080)
Out[3]: 8080
In [4]: get_next_available_port('127.0.0.1', 8080)
Out[4]: 8080
In [5]: get_next_available_port('localhost', 8080)
Out[5]: 8080
```

For me, this means I cant run my tests, as my CI server has a service already running on `8080`

**Comment by adamalton** [comment]
Reminder to myself:

I've fixed this issue in this branch: https://github.com/potatolondon/djangae/commits/fix_get_next_available_port

But if I recall correctly, the tests will fail if you run them while having `runserver` open in another terminal.  This is because the tests have got the port numbers hard coded.  We should add something into `djangae.environment` like `get_blobstore_service_port()` so that there's an easy defacto way of getting the port number.
