### ISSUE TITLE
CloudStorage or Blobstorage to store image

### ISSUE THREAD

**Issue by Ali-aqrabawi** [potatolondon/djangae#787]
i followed the instructions to upload an image to cloud storage but it does not work , no errors no exceptions , but when i go to cloud storage i see nothing ,

image_file = models.ImageField(upload_to='/image/', storage=public_storage)

not sure how to troubleshoot this !

also if i want to use blobstorage can you give an example of how to do it ? in the docs it shows how to do the cloudstorage but not the BlobStorage ,

**Comment by Ali-aqrabawi** [comment]
by the way i followed the instructions to upload an image to cloud storage but it does not work , no errors no exceptions , but when i go to cloud storage i see nothing , 

`image_file = models.ImageField(upload_to='/image/', storage=public_storage)`

not sure how to troubleshoot this !

**Comment by ethagnawl** [comment]
@Ali-aqrabawi Did you ever figure out a solution? If so, could you share an example or point me towards some comprehensive documentation?

**Comment by davidwtbuxton** [comment]
@ethagnawl What problems are you running into? The cloud storage backend will use the local emulated storage stub when running locally with `dev_appserver.py` or `./manage.py runserver`.

The source code says [one can override this to connect to the real cloud storage API][1]. I have never tried this.

[1]: https://github.com/GoogleCloudPlatform/appengine-gcs-client/blob/master/python/src/cloudstorage/storage_api.py#L55

**Comment by davidwtbuxton** [comment]
Vaguely recall that this is a bug:

    image_file = models.ImageField(upload_to='/image/', storage=public_storage)

Instead it should be:

    image_file = models.ImageField(upload_to='image/', storage=public_storage)

**Comment by ethagnawl** [comment]
Thanks for following up, @davidwtbuxton! I've just about sorted out the various issues I was running into, which were mostly silly oversights no my part (namely updating the multipart enctype on the existing form). 

Since it looks like you're affiliated with the project and Potato, I'll also mention that I had trouble figuring out how to reference the uploaded files from my templates but the [virtual-art-sessions](https://github.com/dataarts/virtual-art-sessions/blob/master/udon/views.py#L100) repository contains a working solution that I was able to riff off of. It might be worth adding an example to the Djangae docs and/or a demo app that people could clone and experiment with. If you'd consider accepting a PR for the updated documentation, I'd be willing to submit a PR when I can find some time.

The one last piece of my puzzle is that I'm seeing an error when my tests attempt to upload files. I'm sure it's just a matter of stubbing out the appropriate Google service in my test setup script. Though, again, it'd be really helpful to have a canonical reference for this sort of thing.

Apologies for the wall of text and thanks for putting together/supporting such a useful project!

**Comment by davidwtbuxton** [comment]
For writing unit tests with Django + Djangae, make sure your test case creates a testbed, activates it and configures the blobstore stub. 

https://cloud.google.com/appengine/docs/standard/python/tools/localunittesting

Note that the Djangae settings include the blobstore upload handler, which you can remove if you are not using the BlobstoreStorage backend.

https://github.com/potatolondon/djangae/blob/719e9b2c20/djangae/settings_base.py#L4

The contributed djangae.serve.serve_file helper has logic for setting response size and accepting range headers and serving from the blostore instead of cloud storage. If you don't need that stuff you could do:

    from django.http import HttpResponse
    from google.appengine.ext import blobstore

    def serve(request, filename):
        # Add something like this to urls.py
        #   url(r'^(?P<filename>.*)$', serve),

        bucket = 'my-bucket-name' # Edit.
        object_name = '/gs/{}/{}'.format(bucket, filename)
        blob_key = blobstore.create_gs_key(object_name)
        response = HttpResponse()
        response[blobstore.BLOB_KEY_HEADER] = str(blob_key)

        return response

And it is a _very_ good idea to upload files to a specific folder in cloud storage, then validate that you are serving files only from that folder (in case your project stores other, sensitive files in cloud storage).

**Comment by ethagnawl** [comment]
That's very useful information. Thanks, again, @davidwtbuxton! 

Is there any hope of something similar being rolled into Djangae as a utility class/method? While that solution pretty concise, it'd be nice to not have to copy and paste that solution between different applications.

**Comment by davidwtbuxton** [comment]
> Is there any hope of something similar being rolled into Djangae as a utility class/method?

Well, [`djangae.storage.serve_file`][1] is that functionality, but generalized for use with the blobstore or cloud storage and is a more correct solution because it includes logic for setting response headers for accepting a range, for setting the response content size header, for setting an optional response `content-disposition: attachment` header, etc.

If a project doesn't need that versatility, then I reckon it's fair enough to copy/paste the basic version between projects.

Interesting question is whether this approach (of returning a response with a special blobstore header and no body, relying on appserver to return the file data) works with the newer Python 3 standard runtime. I'm guessing it does, but I haven't tested it.

[1]: https://github.com/potatolondon/djangae/blob/ce8ac22940/djangae/storage.py#L98

**Comment by davidwtbuxton** [comment]
The other approach one can take is to [set the ACL to public][1] for your uploaded files stored in cloud storage (this assumes you never need to restrict access to files) . You can set a default public-read ACL on the bucket itself, or configure the Django storage backend to set a per-object public-read ACL.

If the object has a public-read ACL, you then reference the object with a url like `https://storage.googleapis.com/<bucket>/<filename>` and requests for the file will bypass your app, and be handled by Google's cloud storage servers.

As far as I am aware there's no support in Djangae's cloud storage backend for referencing these public URLs for every uploaded file. You would need to code it yourself.

[1]: https://cloud.google.com/storage/docs/access-public-data

**Comment by davidwtbuxton** [comment]
Strongly recommend using [the `upload_to` argument with Django's file/image field][1] to sort user-generated uploads into date-based folders.

Example:

    class MyModel(models.Model):
        picture = models.ImageField(upload_to='image/%Y/%m/%d/')

If you don't then everything goes into the root of the bucket and when you go to [browse the bucket via Google's cloud console][2] after hundreds, thousands, millions of files have been created you will curse the idiot who didn't use the `upload_to` argument with Django's file/image field to sort user-generated uploads into date-based folders.

I am that idiot.

[1]: https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.FileField.upload_to
[2]: https://console.cloud.google.com/storage/browser

**Comment by ethagnawl** [comment]
> I am that idiot.

I know this feeling well.

> Well, djangae.storage.serve_file is that functionality

Thank you for pointing that out. It makes perfect sense now, but I didn't realize you could just point a URL at this function. I think adding mention of this and/or an example to the documentation could be really useful.

**Comment by adamalton** [comment]
I'm glad that you got this sorted.  Thanks for the knowledge @davidwtbuxton!

> I think adding mention of this and/or an example to the documentation could be really useful.

Wanna send a pull request? :-)

**Comment by ethagnawl** [comment]
> Wanna send a pull request? :-)

I'd be happy to! I'm in the thick of things at work right now, though, so it may take a few days/weeks.

**Comment by adamalton** [comment]
👍
