### ISSUE TITLE
`process_task_queues()` error handling

### ISSUE THREAD

**Issue by stucox** [potatolondon/djangae#914]
Currently, if a task run by `djangae.test.process_task_queues()` returns a non-2xx response, it’s simply logged.

Surely it would be preferable to either:

1. Raise an error — either making the test fail, or for the test to handle (e.g. with `assertRaises()`)
2. Retry the task, as would happen in production — ideally observing retry params, etc

I’d suggest the former should be the default, which may well find hidden bugs in many projects.

It’d be great to have an argument to enable the latter, for use when testing a sharded algorithm’s resilience to errors, for example.

**Comment by adamalton** [comment]
The problem with _2._ is that if you haven't specified a retry limit, then it just retries forever, meaning that whenever you break a test in that way, it just hangs forever instead of giving you a failure.

_1._ sounds like a good idea though, and from a peek at the code looks like a pretty easy change.

**Comment by stucox** [comment]
> The problem with 2. is that if you haven't specified a retry limit, then it just retries forever, meaning that whenever you break a test in that way, it just hangs forever instead of giving you a failure.

There could be a maximum? Or a timeout for the `while tasks:` loop?
