### ISSUE TITLE
connection.queries doesn't show LIMIT being applied

### ISSUE THREAD

**Issue by farridav** [potatolondon/djangae#942]
When using a model backed by the nosql backend, changelist views within Django admin do not have a `LIMIT` clause on them, meaning when you get a lot of nosql model instances, load time increases exponentially for the admin views, eventually making them unusable.

This is because django does a `COUNT * FROM table` before determining whether to use the LIMIT clause, perhaps some sort of an optional admin mixin might help to resolve this?

..Or implementing a count method on the db backend that does smth like https://stackoverflow.com/a/4235169 potentially with some sharded caching on insert/delete..

**Comment by farridav** [comment]
Update: After having read through http://djangae.readthedocs.io/en/latest/pagination/ I thought i might be able to borrow the paginator from there (as it does everything needed), and decorate my model as suggested, but that doesn't seem to work perhaps its not designed to work with django admin, any advice is appreciated

**Comment by adamalton** [comment]
Yes, I'm sort of aware of this problem, but have never put any time into
working out how to solve it.

Can you use a custom ModelAdmin class, and give it a custom queryset that
has a limit on it?  You could make it so that by default is limited to 101
(so that the Django admin knows that there's a 2nd page of results, and
therefore gives you the 'next page' button), and then (by overriding the
get_queryset
<https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_queryset>
method so that you can get hold of the `page` number from the query
string), when you're on page 2, give the queryset an offset of 100 and a
limit of 201.  And when you're on page 3 give it an offset of 200 and a
limit of 301, etc...

I'm thinking out loud here, no idea if that's a good solution.

**Comment by Kazade** [comment]
I'm not sure I understand what the issue is here.. the Django admin should have (by default) a limit of 100 instances per page. Although counting on the Datastore is slow, it does work, so you should see pagination unless the whole site is timing out? Is that the problem, that the pages are too slow?

**Comment by farridav** [comment]
I've been trying to figure out why my nosql admin views are slowing down so I'm use Django debug toolbar, which tells me we are doing a `count * from table` (GQL) which can't work anyway, and proceeding that, a `select * from table` regardless of admin page limits.. 

...but, I tried splicing the queryset, as recommended, and checking `connection.queries`, though there are no LIMIT clauses in any of the statements, but the queryset was reduced (perhaps by python?), could this be that somehow connection queries is not capturing the LIMIT clause even though it's being used ?

**Comment by Kazade** [comment]
Ah! Yes be aware that the SQL printed in connection.queries isn't real SQL, it's pseudo-sql printed out to help debugging - I believe it doesn't currently include LIMIT statements, even if limits are really being applied.

**Comment by farridav** [comment]
Hmm, OK, I had presumed, given the accuracy of the other queries I'm seeing e.g `SELECT * FROM app_model WHERE __key__= aghkZXZ-Tm9uZXIiCxIMZ2FtZXNfcGxheWVyIhBTbG90c3xHYW1lc3lzfDUyDA`, and seeing `LIMIT` on a mysql backend, that the Djangae db backend was also reporting the GQL being used almost verbatim...

But If this is correctly limiting querysets within the admin, and during pagination, we can close this issue, though if its possible to reflect the `LIMIT` in the query that's captured, that may save other developers trying to optimise chasing their tails :)

**Comment by Kazade** [comment]
Yeah, I'll leave this ticket open to improve the pseudo-SQL generated. Thanks for reporting it :)
