### ISSUE TITLE
Breaking change (from SDK), sandbox moved in 1.9.60

### ISSUE THREAD

**Issue by farridav** [potatolondon/djangae#964]
Having updated the SDK to the latest build, alot of classes have moved inside a `runtime` package, to resolve the issue I have replaced `google.appengine.tools.devappserver2.python`  with `google.appengine.tools.devappserver2.python.runtime` in all of the Djangae imports

**Comment by adamalton** [comment]
I think we should make changes to support the new SDK and just `try/except` the imports that have changed (so that we don't break things for people using the older SDK (for now)).

In other words, after the changes, the djangae test suite should work _both_ when `APPENGINE_SDK_VERSION` in `testapp/install_deps.py` is set to its current value of `"1.9.54"`, _and_ when it's set to`"1.9.60"`.  Once we know it works with both, we can update that to `"1.9.60"`.

Where necessary, we can do `import x as thing` in order to avoid issues where the actual module name has changed (e.g. where `python_runtime` has changed to `instance_factory`).

Happy to accept a pull request for this.

**Comment by farridav** [comment]
I have been pondering on this, and Google refactoring their SDK is nothing new, nor are the breaking changes that come with it, which is all to be expected given Djangae has to use an unoffical API (SDK internals) to integrate Django so seemlessly.

We could make a `djangae/compat.py` file, and import all the SDK libs/functions from there, so when there is a new SDK release, and things have moved around, we need only:


```
# djangae/compat.py
current_version = _VersionList(sdk_update_checker.GetVersionObject()['release'])
if current_version == 123:
    from place import thing
elif [...]
    from other.place import thing

#djangae/management/runserver.py
from djangae.compat import thing
```

Rather than litter the Djangae codebase with try/except imports and version checks, this would also allow contributors (like me) to make consistent, backwards compatible fixes in an easy way ...

As a bonus, we could even iterate all supported SDK versions, and assert we can import `djangae/compat.py` without raising any `ImportError`'s.

Keen to hear thoughts on this...

**Comment by telenieko** [comment]
It looks like the breaking change is not from 1.9.60 but from earlier on. 1.9.57 is the last version that works.

I am new to djangae (long time django user) and this drove me crazy. Maybe a note can be put on the README alerting users they MUST use 1.9.57 or ealier until this is fixed?

**Comment by adamalton** [comment]
@farridav I quite like your djangae/compat.py idea.  I suggest that we only use it for imports which are different between different SDK versions (i.e. we don't want to import _all_ the SDK stuff via djangae.compat).

Happy to accept a PR which uses your approach.
